Description: Downloads the latest version of InstallmacOSApplication and imports it into Munki.
Identifier: com.github.arequ.download.InstallmacOSApplication
MinimumVersion: '1.0.0'

Input:
  APP_FILENAME: InstallmacOSApplication
  NAME: InstallmacOSApplication

Process:
- Processor: com.github.arequ.SharedProcessors/GetInstallmacOSMetadata
  Output:
  - url
  - display_name
  - version
  - build

- Processor: com.github.arequ.SharedProcessors/URLDownloader
  Arguments:
    filename: '%display_name%-%build%.pkg'
    url: '%url%'

- Processor: CodeSignatureVerifier
  Arguments:
    input_path: '%pathname%'
    expected_authority_name:
    - Software Update
    - Apple Software Update Certification Authority
    - Apple Root CA